### ISSUE TITLE
Group of CIs

### ISSUE THREAD

**Issue by rogermartensson** [jonnyt/posh-itop#1]
Looking into creating an audit process and found this very nice module.
I wonder if you'll think about adding cmdlets to manage and using Group of CIs.
If not I might look into adding it myself since we might be needing it.

**Comment by rogermartensson** [comment]
Ok. It wasn't that hard to add "Group of CIs".
To whoever reads this. Add this to itop.psm1 and you have another cmdlet.

Function Get-iTopGroup
{
    Param(
        [Parameter(Mandatory=$True)][PSCredential]$credentials,
        [Parameter(Mandatory=$True)][string]$uri,
        [Parameter(Mandatory=$False)][string]$oqlFilter,
        [Parameter(Mandatory=$False)][string]$outputFields='*'
    )

```
Get-iTopObject -objectClass 'Group' -ouputFields $outputFields -uri $uri -credentials $credentials -oqlFilter $oqlFilter
```

}

Export-ModuleMember -Function Get-iTopGroup

**Comment by jonnyt** [comment]
Thanks for this and sorry for the long delay.  I'm more actively watching this now so will incorporate your function.
