### ISSUE TITLE
Missing CI

### ISSUE THREAD

**Issue by rogermartensson** [jonnyt/posh-itop#2]
Hi!

Thank you for adding Groups.
I have noticed some other Cmdlets that are missing and that is for these CI:s.
- WebServer
- WebApplication
- DatabaseSchema

It was pretty easy to add (copy, paste, change one parameter) but I guess you'll want add help texts etc.

**Comment by jonnyt** [comment]
Hey there, I'm a bit slow on the updates, but if you've already adding those things you need I'm happy to add you as a collaborator so that you can issue pull requests.

**Comment by rogermartensson** [comment]
This is old and you've already added these. Can be closed.
